### ISSUE TITLE
Multiple outputs for e.g. webpdf, pandoc

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/nbconvert-feedstock#46]
Hey folks! 

Over on https://github.com/conda-forge/staged-recipes/pull/12516#discussion_r502814168 we've been chatting about the tradeoffs of offering a `jupyter-book-webpdf`, which would be somewhat simpler if there was an `nbconvert-webpdf` which already carried the `pyppeteer` pin, beyond what `run_constrained` would do.

However we solve it over there, we could take the opportunity to offer, a la `matplotlib[-base]`
- `nbconvert-core` (which could be `noarch: python`) that still carried all the `run_constrained` pieces, but was lighter-weight and -featured (#24)
- `nbconvert` that actually required `pandoc`, and therefore could not be `noarch: python`, for now
- `nbconvert-webpdf` that acutally required `pyppeteer`, and could actually _also_ be `noarch: python`

It would take a while (or maybe a migration) to get everything that didn't specifically _need_ the `pandoc` capability to use `-core`, but eventually, maybe, (more) people could be happy(er).

I'm happy to work up a PR if people think this is a good idea.

**Comment by ocefpaf** [comment]
I don't have strong opinions about this but I'd love to get the input from the upstream devs of nbconvert. (I'm guessing you are one of them, right?)

Can you bring this up with them and get their opinion on this?

**Comment by bollwyvl** [comment]
From the nbconvert issue, we've got one :+1: from the most active maintainer... we can let it cook for a while, but i can knock together a wip PR...

**Comment by ocefpaf** [comment]
If the most active maintainer is happy, go for it!

**Comment by bollwyvl** [comment]
Welp, here we go: #47
