### ISSUE TITLE
Add a hint for pandoc and miktex on windows?

### ISSUE THREAD

**Issue by janschulz** [conda-forge/nbconvert-feedstock#5]
conda-forge now includes a latex environment (miktex) and pandoc, both repackaged binaries from upstream.

I'm not sure if this should get a real dependency or better "just" an error message which basically says that these packages should be installed into the root environment (no need to install it into all environments where nbconvert is installed, especially if the notebook is started without activating the specific environment first, which then would not have the executables in PATH -> as the root environment is always kept in PATH and is added to PATH by the miniconda installer, installed binaries in the root environment work even in sub-environments).

**Comment by jakirkham** [comment]
Though that is only Windows at this point.

Not sure how I feel about making it a dependency as latex installs tend to be a bit bulky. An error would be bad (like in a post-link script) as that would stop the install of `nbconvert` so basically would be a less nice dependency. Maybe a warning message (with no error) in a post-link script. It would only be the Windows post-link script. Alternatively, we could a Readme with the recipe explaining that installing latex and pandoc are options for PDF conversion.

**Comment by janschulz** [comment]
What would be ideal is a "dependency in the root env", so apps don't get installed multiple times... Although at least miktex is small (compared to a full texlive install... still 200MB) as it only installs the main things into the env and the rest are installed on the fly into the user profile dir.

Isn't there a new "long description" field in meta.yml which would be shown in GUIs like the new notebook extension for maintaining envs? Together with a postinstall script that would probably be enough...

**Comment by minrk** [comment]
It seems appropriate to depend on pandoc, at least. I'm a little less sure about latex, but possibly.

**Comment by michaelpacer** [comment]
NB: Pandoc was included in the conda forge feedstocks for nbconvert 5.0.0 and 5.1.1.
