### ISSUE TITLE
Create a prerelease RC branch

### ISSUE THREAD

**Issue by jasongrout** [conda-forge/nbconvert-feedstock#58]
I just pushed a commit to create an `rc` branch to release rc releases on the `nbconvert_rc` label: eb6957d

I'll close this issue immediately, but just wanted to log somewhere that this happened.

**Comment by jasongrout** [comment]
Looks like I messed this one up. I was trying to create an RC branch on the nbconvert feedstock, so I pushed the first RC recipe directly to the rc branch. However, I forgot that the recipe needs to be rerendered to make the conda label take effect. The end result is it looks like the 6.2.0rc0 package was published to the main channel: https://anaconda.org/conda-forge/nbconvert/files

@conda-forge-admin - should we mark the 6.2.0rc0 package as broken on the main channel, so it doesn't get installed accidentally from the main channel when people are expecting a stable release? I have an rc1 build with the proper label building over in https://github.com/conda-forge/nbconvert-feedstock/pull/59

**Comment by jasongrout** [comment]
I requested these be marked as broken at https://github.com/conda-forge/admin-requests/pull/307

**Comment by jakirkham** [comment]
JFYI @conda-forge-admin is a bot and doesn't contact core

Yeah marking it broken makes sense. Then would follow [these docs]( https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds ) to setup the RC branch.

**Comment by jasongrout** [comment]
> Yeah marking it broken makes sense. Then would follow [these docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds) to setup the RC branch.

Thanks. Well, now that the RC branch is created, #59 follows those docs to make a PR. 

My dilemma before was that I couldn't create a PR to the rc branch until it was created, so I thought I would push my first prerelease directly to the rc branch. Instead, should I have created an rc branch as a mirror of the master branch, then did my first prerelease as a PR to that newly-created rc branch?

**Comment by jakirkham** [comment]
Normally one just creates the branch on top of `master` or other appropriate existing commit. That avoids uploading new packages and gives a place for PRs to be made against.

**Comment by jasongrout** [comment]
> Normally one just creates the branch on top of `master` or other appropriate existing commit. That avoids uploading new packages and gives a place for PRs to be made against.

Excellent, thanks.
